project:
  type: book
  output-dir: docs

book:
  title: "DataViz Portfolio"
  author: "Boyd Tarlinton"
  number-sections: false
  chapters:
    - index.qmd
    - part: "TidyTuesday Projects"
      chapters:
        - 2022-08-30.qmd
        - 2022-08-23.qmd
        - 2022-08-16.qmd
        - 2022-08-09.qmd
  page-footer:
    right:
      - text: "{{< fa brands twitter  size=large >}}"
        href: https://twitter.com/bioboyd
      - text: "{{< fa brands linkedin  size=large >}}"
        href: https://www.linkedin.com/in/boyd-tarlinton/
      - text: "{{< fa brands github  size=large >}}"
        href: https://github.com/B0ydT/
      - text: "{{< fa at  size=large >}}"
        href: mailto:b2.tarlinton@qut.edu.au
      - text: "{{< fa brands orcid  size=large >}}"
        href: https://orcid.org/0000-0002-4146-7083
    left: 
      - text: "Copyright 2020, Boyd Tarlinton, CC BY 4.0"
        href: LICENSE.md

format:
  html:
    theme: cosmo
    df-print: kable
    toc: true
    number-sections: false